apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    prometheus: cluster
  name: rule-kubelet 
  namespace: kube-system
spec:
  groups:
    - name: kubelet.rules
      rules:
        - alert: K8SKubeletDown
          expr: absent(up{job="kubernetes-nodes"} == 1)
          for: 1h
          labels:
            channel: sk-cps-ops
            severity: critical
          annotations:
            description: Prometheus failed to scrape {{ $labels.instance }} of kubelets.
            summary: Kubelets cannot be scraped
        - alert: K8SKubeletTooManyPods
          expr: kubelet_running_pod_count > 100
          for: 10m
          labels:
            channel: sk-cps-ops
            severity: warning
          annotations:
            description: Kubelet {{$labels.instance}} is running {{$value}} pods, close to the limit of 100
            summary: Kubelet is close to pod limit
